version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    env_file: .env
    networks:
      - backend
    restart: on-failure

  db:
    image: mariadb:10
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    env_file: .env
    networks:
      - backend
    restart: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - backend
    restart: on-failure

volumes:
  static_volume:

networks:
  backend:
