version: "3"

services:
  app:
    build: .
    depends_on:
      - db
    env_file: .env
    networks:
      - backend

  db:
    image: mariadb:10
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    env_file: .env
    networks:
      - backend

networks:
  backend:
